use std::fmt::Debug;

use yasna::models::ObjectIdentifier;
use yasna::{DERWriter, Tag};

use crate::{oid, Issuer, KeyIdMethod, SigningKey};

/// An X.509 extension whose OID and criticality are fixed by the profile
/// defining it.
///
/// Implementors receive [`Extension`] through a blanket impl. Extensions that
/// decide criticality (or OID) at runtime implement [`Extension`] directly
/// instead.
pub(crate) trait StaticExtension: Debug {
	/// The OID components of the extension.
	const OID: &'static [u64];

	/// The criticality of the extension.
	const CRITICALITY: Criticality;

	/// Write the extension's value (the content of the extnValue OCTET STRING).
	fn write_value(&self, writer: DERWriter);
}

impl<T: StaticExtension> Extension for T {
	fn oid(&self) -> &[u64] {
		T::OID
	}

	fn criticality(&self) -> Criticality {
		T::CRITICALITY
	}

	fn write_value(&self, writer: DERWriter) {
		// Calling with fully qualified syntax to disambiguate.
		StaticExtension::write_value(self, writer)
	}
}

/// An X.509 extension.
///
/// All extensions have an OID, a criticality, and a DER encoded value for inclusion in
/// an X.509 extension SEQUENCE.
pub(crate) trait Extension: Debug {
	/// Return the OID components of the extension.
	fn oid(&self) -> &[u64];

	/// Return the criticality of the extension.
	fn criticality(&self) -> Criticality;

	/// Write the extension's value (the content of the extnValue OCTET STRING).
	fn write_value(&self, writer: DERWriter);
}

/// The criticality of an X.509 extension.
///
/// This controls how consumers should handle an unrecognized extension.
///
/// See [RFC 5280 §4.2] for more information.
///
/// [RFC 5280 §4.2]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2>
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub(crate) enum Criticality {
	/// The extension MUST be recognized and parsed correctly.
	Critical,

	/// The extension MAY be ignored if it is not recognized.
	NonCritical,
}

impl From<bool> for Criticality {
	fn from(critical: bool) -> Self {
		match critical {
			true => Self::Critical,
			false => Self::NonCritical,
		}
	}
}

/// Serializes an X.509v3 extension according to RFC 5280.
pub(crate) fn write_extension(writer: DERWriter, extension: &dyn Extension) {
	/*
	   Extension  ::=  SEQUENCE  {
			extnID      OBJECT IDENTIFIER,
			critical    BOOLEAN DEFAULT FALSE,
			extnValue   OCTET STRING
						-- contains the DER encoding of an ASN.1 value
						-- corresponding to the extension type identified
						-- by extnID
			}
	*/
	writer.write_sequence(|writer| {
		writer
			.next()
			.write_oid(&ObjectIdentifier::from_slice(extension.oid()));
		// DER requires that DEFAULT values be omitted (X.690 §11.5): the critical
		// flag may only be encoded when it is TRUE.
		if extension.criticality() == Criticality::Critical {
			writer.next().write_bool(true);
		}
		writer.next().write_bytes(&yasna::construct_der(|writer| {
			extension.write_value(writer)
		}));
	})
}

/// An X.509v3 authority key identifier extension according to [RFC 5280 §4.2.1.1].
///
/// RFC 5280 states:
///   'The keyIdentifier field of the authorityKeyIdentifier extension MUST
///    be included in all certificates generated by conforming CAs to
///    facilitate certification path construction.  There is one exception;
///    where a CA distributes its public key in the form of a "self-signed"
///    certificate, the authority key identifier MAY be omitted.'
/// In addition, for CRLs:
///    'Conforming CRL issuers MUST use the key identifier method, and MUST
///     include this extension in all CRLs issued.'
///
/// [RFC 5280 §4.2.1.1]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.1>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct AuthorityKeyIdentifier(pub(crate) Vec<u8>);

impl<S: SigningKey> From<&Issuer<'_, S>> for AuthorityKeyIdentifier {
	fn from(issuer: &Issuer<'_, S>) -> Self {
		Self(match issuer.key_identifier_method.as_ref() {
			KeyIdMethod::PreSpecified(aki) => aki.clone(),
			#[cfg(feature = "crypto")]
			_ => issuer
				.key_identifier_method
				.derive(issuer.signing_key.subject_public_key_info()),
		})
	}
}

impl StaticExtension for AuthorityKeyIdentifier {
	const OID: &'static [u64] = oid::AUTHORITY_KEY_IDENTIFIER;

	// RFC 5280 §4.2.1.1: "Conforming CAs MUST mark this extension as non-critical."
	const CRITICALITY: Criticality = Criticality::NonCritical;

	fn write_value(&self, writer: DERWriter) {
		/*
			AuthorityKeyIdentifier ::= SEQUENCE {
				   keyIdentifier             [0] KeyIdentifier           OPTIONAL,
				   authorityCertIssuer       [1] GeneralNames            OPTIONAL,
				   authorityCertSerialNumber [2] CertificateSerialNumber OPTIONAL  }
			KeyIdentifier ::= OCTET STRING
		*/
		writer.write_sequence(|writer| {
			writer
				.next()
				.write_tagged_implicit(Tag::context(0), |writer| writer.write_bytes(&self.0))
		});
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn critical_flag_omitted_when_false() {
		// The critical flag is DEFAULT FALSE, so DER (X.690 §11.5) requires that a
		// non-critical extension omit it entirely rather than encode FALSE.
		// See https://github.com/rustls/rcgen/pull/444 for a past instance of this
		// bug class.
		let ext = DummyExt(Criticality::NonCritical);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(ext.oid()));
					// No BOOLEAN between the OID and the value: the critical
					// flag must be absent, not encoded as FALSE.
					writer
						.next()
						.write_bytes(&yasna::construct_der(|writer| ext.write_value(writer)));
				})
			})
		);
	}

	#[test]
	fn critical_flag_written_when_true() {
		let ext = DummyExt(Criticality::Critical);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(ext.oid()));
					writer.next().write_bool(true); // critical TRUE
					writer
						.next()
						.write_bytes(&yasna::construct_der(|writer| ext.write_value(writer)));
				})
			})
		);
	}

	#[test]
	fn aki_encoding() {
		let ext = AuthorityKeyIdentifier(vec![0xDE, 0xAD]);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(oid::AUTHORITY_KEY_IDENTIFIER));
					// Non-critical: the critical flag must be absent.
					writer.next().write_bytes(&yasna::construct_der(|writer| {
						// AuthorityKeyIdentifier ::= SEQUENCE { keyIdentifier [0] OCTET STRING }
						writer.write_sequence(|writer| {
							writer
								.next()
								.write_tagged_implicit(Tag::context(0), |writer| {
									writer.write_bytes(&[0xDE, 0xAD])
								})
						})
					}));
				})
			})
		);
	}

	#[derive(Debug)]
	struct DummyExt(Criticality);

	impl Extension for DummyExt {
		fn oid(&self) -> &[u64] {
			&[1, 3, 6, 1, 4, 1, 99]
		}

		fn criticality(&self) -> Criticality {
			self.0
		}

		fn write_value(&self, writer: DERWriter) {
			writer.write_null()
		}
	}
}
