use std::fmt::Debug;
use std::net::IpAddr;

use yasna::models::ObjectIdentifier;
use yasna::{DERWriter, Tag};

use crate::{
	oid, write_distinguished_name, CertificateParams, ExtendedKeyUsagePurpose, GeneralSubtree,
	Issuer, KeyIdMethod, KeyUsagePurpose, SanType, SigningKey,
};

/// An X.509 extension whose OID and criticality are fixed by the profile
/// defining it.
///
/// Implementors receive [`Extension`] through a blanket impl. Extensions that
/// decide criticality (or OID) at runtime implement [`Extension`] directly
/// instead.
pub(crate) trait StaticExtension: Debug {
	/// The OID components of the extension.
	const OID: &'static [u64];

	/// The criticality of the extension.
	const CRITICALITY: Criticality;

	/// Write the extension's value (the content of the extnValue OCTET STRING).
	fn write_value(&self, writer: DERWriter);
}

impl<T: StaticExtension> Extension for T {
	fn oid(&self) -> &[u64] {
		T::OID
	}

	fn criticality(&self) -> Criticality {
		T::CRITICALITY
	}

	fn write_value(&self, writer: DERWriter) {
		// Calling with fully qualified syntax to disambiguate.
		StaticExtension::write_value(self, writer)
	}
}

/// An X.509 extension.
///
/// All extensions have an OID, a criticality, and a DER encoded value for inclusion in
/// an X.509 extension SEQUENCE.
pub(crate) trait Extension: Debug {
	/// Return the OID components of the extension.
	fn oid(&self) -> &[u64];

	/// Return the criticality of the extension.
	fn criticality(&self) -> Criticality;

	/// Write the extension's value (the content of the extnValue OCTET STRING).
	fn write_value(&self, writer: DERWriter);
}

/// The criticality of an X.509 extension.
///
/// This controls how consumers should handle an unrecognized extension.
///
/// See [RFC 5280 §4.2] for more information.
///
/// [RFC 5280 §4.2]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2>
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub(crate) enum Criticality {
	/// The extension MUST be recognized and parsed correctly.
	Critical,

	/// The extension MAY be ignored if it is not recognized.
	NonCritical,
}

impl From<bool> for Criticality {
	fn from(critical: bool) -> Self {
		match critical {
			true => Self::Critical,
			false => Self::NonCritical,
		}
	}
}

/// Serializes an X.509v3 extension according to RFC 5280.
pub(crate) fn write_extension(writer: DERWriter, extension: &dyn Extension) {
	/*
	   Extension  ::=  SEQUENCE  {
			extnID      OBJECT IDENTIFIER,
			critical    BOOLEAN DEFAULT FALSE,
			extnValue   OCTET STRING
						-- contains the DER encoding of an ASN.1 value
						-- corresponding to the extension type identified
						-- by extnID
			}
	*/
	writer.write_sequence(|writer| {
		writer
			.next()
			.write_oid(&ObjectIdentifier::from_slice(extension.oid()));
		// DER requires that DEFAULT values be omitted (X.690 §11.5): the critical
		// flag may only be encoded when it is TRUE.
		if extension.criticality() == Criticality::Critical {
			writer.next().write_bool(true);
		}
		writer.next().write_bytes(&yasna::construct_der(|writer| {
			extension.write_value(writer)
		}));
	})
}

/// An X.509v3 authority key identifier extension according to [RFC 5280 §4.2.1.1].
///
/// RFC 5280 states:
///   'The keyIdentifier field of the authorityKeyIdentifier extension MUST
///    be included in all certificates generated by conforming CAs to
///    facilitate certification path construction.  There is one exception;
///    where a CA distributes its public key in the form of a "self-signed"
///    certificate, the authority key identifier MAY be omitted.'
/// In addition, for CRLs:
///    'Conforming CRL issuers MUST use the key identifier method, and MUST
///     include this extension in all CRLs issued.'
///
/// [RFC 5280 §4.2.1.1]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.1>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct AuthorityKeyIdentifier(pub(crate) Vec<u8>);

impl<S: SigningKey> From<&Issuer<'_, S>> for AuthorityKeyIdentifier {
	fn from(issuer: &Issuer<'_, S>) -> Self {
		Self(match issuer.key_identifier_method.as_ref() {
			KeyIdMethod::PreSpecified(aki) => aki.clone(),
			#[cfg(feature = "crypto")]
			_ => issuer
				.key_identifier_method
				.derive(issuer.signing_key.subject_public_key_info()),
		})
	}
}

impl StaticExtension for AuthorityKeyIdentifier {
	const OID: &'static [u64] = oid::AUTHORITY_KEY_IDENTIFIER;

	// RFC 5280 §4.2.1.1: "Conforming CAs MUST mark this extension as non-critical."
	const CRITICALITY: Criticality = Criticality::NonCritical;

	fn write_value(&self, writer: DERWriter) {
		/*
			AuthorityKeyIdentifier ::= SEQUENCE {
				   keyIdentifier             [0] KeyIdentifier           OPTIONAL,
				   authorityCertIssuer       [1] GeneralNames            OPTIONAL,
				   authorityCertSerialNumber [2] CertificateSerialNumber OPTIONAL  }
			KeyIdentifier ::= OCTET STRING
		*/
		writer.write_sequence(|writer| {
			writer
				.next()
				.write_tagged_implicit(Tag::context(0), |writer| writer.write_bytes(&self.0))
		});
	}
}

/// An X.509v3 subject alternative name extension according to [RFC 5280 §4.2.1.6].
///
/// [RFC 5280 §4.2.1.6]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.6>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct SubjectAlternativeName<'params> {
	criticality: Criticality,
	names: &'params [SanType],
}

impl<'params> SubjectAlternativeName<'params> {
	pub(crate) fn from_params(params: &'params CertificateParams) -> Option<Self> {
		// GeneralNames ::= SEQUENCE SIZE (1..MAX): an empty SAN can't be encoded,
		// so the extension is omitted (RFC 5280 §4.2.1.6).
		if params.subject_alt_names.is_empty() {
			return None;
		}

		Some(Self {
			// Per RFC 5280 §4.1.2.6, SAN must be marked critical if the subject
			// is an empty sequence, and SHOULD be non-critical otherwise.
			criticality: params.distinguished_name.entries.is_empty().into(),
			names: &params.subject_alt_names,
		})
	}

	fn write_name(writer: DERWriter, san: &SanType) {
		writer.write_tagged_implicit(Tag::context(san.tag()), |writer| match san {
			SanType::Rfc822Name(name) | SanType::DnsName(name) | SanType::URI(name) => {
				writer.write_ia5_string(name.as_str())
			},
			SanType::IpAddress(IpAddr::V4(addr)) => writer.write_bytes(&addr.octets()),
			SanType::IpAddress(IpAddr::V6(addr)) => writer.write_bytes(&addr.octets()),
			SanType::OtherName((oid, value)) => {
				// otherName SEQUENCE { OID, [0] explicit any defined by oid }
				// https://datatracker.ietf.org/doc/html/rfc5280#page-38
				writer.write_sequence(|writer| {
					writer.next().write_oid(&ObjectIdentifier::from_slice(oid));
					value.write_der(writer.next());
				});
			},
		})
	}
}

impl Extension for SubjectAlternativeName<'_> {
	fn oid(&self) -> &[u64] {
		oid::SUBJECT_ALT_NAME
	}

	fn criticality(&self) -> Criticality {
		self.criticality
	}

	fn write_value(&self, writer: DERWriter) {
		/*
		   SubjectAltName ::= GeneralNames
		   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName
		*/
		writer.write_sequence(|writer| {
			for san in self.names.iter() {
				Self::write_name(writer.next(), san);
			}
		});
	}
}

/// An X.509v3 key usage extension according to [RFC 5280 §4.2.1.3].
///
/// [RFC 5280 §4.2.1.3]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.3>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct KeyUsage<'params>(&'params [KeyUsagePurpose]);

impl<'params> KeyUsage<'params> {
	pub(crate) fn from_params(params: &'params CertificateParams) -> Option<Self> {
		if params.key_usages.is_empty() {
			return None;
		}

		Some(Self(&params.key_usages))
	}
}

impl StaticExtension for KeyUsage<'_> {
	const OID: &'static [u64] = oid::KEY_USAGE;

	// RFC 5280 §4.2.1.3: "When present, conforming CAs SHOULD mark this extension
	// as critical."
	const CRITICALITY: Criticality = Criticality::Critical;

	fn write_value(&self, writer: DERWriter) {
		/*
		   KeyUsage ::= BIT STRING {
			  digitalSignature        (0),
			  nonRepudiation          (1), -- recent editions of X.509 have
										   -- renamed this bit to contentCommitment
			  keyEncipherment         (2),
			  dataEncipherment        (3),
			  keyAgreement            (4),
			  keyCertSign             (5),
			  cRLSign                 (6),
			  encipherOnly            (7),
			  decipherOnly            (8) }
		*/
		// u16 is large enough to encode the largest possible key usage (two-bytes)
		let bit_string = self.0.iter().fold(0u16, |bit_string, key_usage| {
			bit_string | key_usage.to_u16()
		});

		match u16::BITS - bit_string.trailing_zeros() {
			bits @ 0..=8 => {
				writer.write_bitvec_bytes(&bit_string.to_be_bytes()[..1], bits as usize)
			},
			bits @ 9..=16 => writer.write_bitvec_bytes(&bit_string.to_be_bytes(), bits as usize),
			_ => unreachable!(),
		}
	}
}

/// An X.509v3 extended key usage extension according to [RFC 5280 §4.2.1.12].
///
/// [RFC 5280 §4.2.1.12]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.12>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ExtendedKeyUsage<'params>(&'params [ExtendedKeyUsagePurpose]);

impl<'params> ExtendedKeyUsage<'params> {
	pub(crate) fn from_params(params: &'params CertificateParams) -> Option<Self> {
		if params.extended_key_usages.is_empty() {
			return None;
		}

		Some(Self(&params.extended_key_usages))
	}
}

impl StaticExtension for ExtendedKeyUsage<'_> {
	const OID: &'static [u64] = oid::EXT_KEY_USAGE;

	// RFC 5280 §4.2.1.12: "This extension MAY, at the option of the certificate
	// issuer, be either critical or non-critical."
	// TODO(XXX): make this configurable?
	const CRITICALITY: Criticality = Criticality::NonCritical;

	fn write_value(&self, writer: DERWriter) {
		/*
		   ExtKeyUsageSyntax ::= SEQUENCE SIZE (1..MAX) OF KeyPurposeId
		   KeyPurposeId ::= OBJECT IDENTIFIER
		*/
		writer.write_sequence(|writer| {
			for usage in self.0.iter() {
				writer
					.next()
					.write_oid(&ObjectIdentifier::from_slice(usage.oid()));
			}
		});
	}
}

/// An X.509v3 name constraints extension according to [RFC 5280 §4.2.1.10].
///
/// [RFC 5280 §4.2.1.10]: <https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.10>
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct NameConstraints<'params> {
	permitted_subtrees: &'params [GeneralSubtree],
	excluded_subtrees: &'params [GeneralSubtree],
}

impl<'params> NameConstraints<'params> {
	pub(crate) fn from_params(params: &'params CertificateParams) -> Option<Self> {
		match &params.name_constraints {
			// If both subtrees are empty, the extension must be omitted.
			Some(nc) if !nc.is_empty() => Some(Self {
				permitted_subtrees: &nc.permitted_subtrees,
				excluded_subtrees: &nc.excluded_subtrees,
			}),
			_ => None,
		}
	}

	fn write_general_subtrees(writer: DERWriter, tag: u64, general_subtrees: &[GeneralSubtree]) {
		/*
		   GeneralSubtrees ::= SEQUENCE SIZE (1..MAX) OF GeneralSubtree
		   GeneralSubtree ::= SEQUENCE {
				base                    GeneralName,
				minimum         [0]     BaseDistance DEFAULT 0,
				maximum         [1]     BaseDistance OPTIONAL }
		   BaseDistance ::= INTEGER (0..MAX)
		*/
		writer.write_tagged_implicit(Tag::context(tag), |writer| {
			writer.write_sequence(|writer| {
				for subtree in general_subtrees.iter() {
					writer.next().write_sequence(|writer| {
						let writer = writer.next();
						let tag = Tag::context(subtree.tag());
						match subtree {
							GeneralSubtree::Rfc822Name(name) | GeneralSubtree::DnsName(name) => {
								writer.write_tagged_implicit(tag, |writer| {
									writer.write_ia5_string(name)
								})
							},
							// `Name` is a CHOICE, so X.680 §31.2.7 requires explicit tagging.
							GeneralSubtree::DirectoryName(name) => writer
								.write_tagged(tag, |writer| write_distinguished_name(writer, name)),
							GeneralSubtree::IpAddress(subnet) => writer
								.write_tagged_implicit(tag, |writer| {
									writer.write_bytes(&subnet.to_bytes())
								}),
						}
						// minimum must be 0 (the default) and maximum must be absent
					});
				}
			});
		});
	}
}

impl StaticExtension for NameConstraints<'_> {
	const OID: &'static [u64] = oid::NAME_CONSTRAINTS;

	// RFC 5280 §4.2.1.10: "Conforming CAs MUST mark this extension as critical."
	const CRITICALITY: Criticality = Criticality::Critical;

	fn write_value(&self, writer: DERWriter) {
		/*
		   NameConstraints ::= SEQUENCE {
				permittedSubtrees       [0]     GeneralSubtrees OPTIONAL,
				excludedSubtrees        [1]     GeneralSubtrees OPTIONAL }
		*/
		writer.write_sequence(|writer| {
			if !self.permitted_subtrees.is_empty() {
				Self::write_general_subtrees(writer.next(), 0, self.permitted_subtrees);
			}
			if !self.excluded_subtrees.is_empty() {
				Self::write_general_subtrees(writer.next(), 1, self.excluded_subtrees);
			}
		});
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn critical_flag_omitted_when_false() {
		// The critical flag is DEFAULT FALSE, so DER (X.690 §11.5) requires that a
		// non-critical extension omit it entirely rather than encode FALSE.
		// See https://github.com/rustls/rcgen/pull/444 for a past instance of this
		// bug class.
		let ext = DummyExt(Criticality::NonCritical);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(ext.oid()));
					// No BOOLEAN between the OID and the value: the critical
					// flag must be absent, not encoded as FALSE.
					writer
						.next()
						.write_bytes(&yasna::construct_der(|writer| ext.write_value(writer)));
				})
			})
		);
	}

	#[test]
	fn critical_flag_written_when_true() {
		let ext = DummyExt(Criticality::Critical);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(ext.oid()));
					writer.next().write_bool(true); // critical TRUE
					writer
						.next()
						.write_bytes(&yasna::construct_der(|writer| ext.write_value(writer)));
				})
			})
		);
	}

	#[test]
	fn aki_encoding() {
		let ext = AuthorityKeyIdentifier(vec![0xDE, 0xAD]);
		let der = yasna::construct_der(|writer| write_extension(writer, &ext));
		assert_eq!(
			der,
			yasna::construct_der(|writer| {
				writer.write_sequence(|writer| {
					writer
						.next()
						.write_oid(&ObjectIdentifier::from_slice(oid::AUTHORITY_KEY_IDENTIFIER));
					// Non-critical: the critical flag must be absent.
					writer.next().write_bytes(&yasna::construct_der(|writer| {
						// AuthorityKeyIdentifier ::= SEQUENCE { keyIdentifier [0] OCTET STRING }
						writer.write_sequence(|writer| {
							writer
								.next()
								.write_tagged_implicit(Tag::context(0), |writer| {
									writer.write_bytes(&[0xDE, 0xAD])
								})
						})
					}));
				})
			})
		);
	}

	#[test]
	fn name_constraints_absent_when_subtrees_empty() {
		// A name constraints extension with no permitted or excluded subtrees
		// would violate SEQUENCE SIZE (1..MAX) and must be omitted.
		let params = CertificateParams {
			name_constraints: Some(crate::NameConstraints {
				permitted_subtrees: Vec::new(),
				excluded_subtrees: Vec::new(),
			}),
			..CertificateParams::default()
		};
		assert!(NameConstraints::from_params(&params).is_none());
	}

	#[test]
	fn san_absent_when_no_names() {
		assert!(SubjectAlternativeName::from_params(&CertificateParams::default()).is_none());
	}

	#[test]
	fn san_critical_when_subject_empty() {
		// RFC 5280 §4.1.2.6: SAN must be critical if the subject is an empty sequence.
		let mut params = CertificateParams {
			subject_alt_names: vec![SanType::DnsName("example.com".try_into().unwrap())],
			..CertificateParams::default()
		};
		assert_eq!(
			SubjectAlternativeName::from_params(&params)
				.unwrap()
				.criticality(),
			Criticality::NonCritical
		);

		params.distinguished_name = crate::DistinguishedName::new();
		assert_eq!(
			SubjectAlternativeName::from_params(&params)
				.unwrap()
				.criticality(),
			Criticality::Critical
		);
	}

	#[derive(Debug)]
	struct DummyExt(Criticality);

	impl Extension for DummyExt {
		fn oid(&self) -> &[u64] {
			&[1, 3, 6, 1, 4, 1, 99]
		}

		fn criticality(&self) -> Criticality {
			self.0
		}

		fn write_value(&self, writer: DERWriter) {
			writer.write_null()
		}
	}
}
